schema {
	query : Query
	mutation : Mutation
}

type Query {
	userFind : [User]
}

type Mutation {
	userCreate(form: UserForm): User
}

type User {
	id : Int
	username : String
	email: String
	id_role: Int
	password: String
}

input UserForm {
	username : String
	password: String
	email: String
	id_role: Int
}
